In [19]:
import pandas as pd
path="/content/train (2).csv"
dd=pd.read_csv(path)
print(dd.head(5))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [20]:
dd.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
mean_age=dd['Age'].mean()
dd['Age'].fillna(mean_age,inplace=True)

In [22]:
dd.drop(columns=['Cabin'],axis=1,inplace=True)
print(dd.head(5))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Embarked
0      0         A/5 21171   7.2500        S
1      0          PC 17599  71.2833        C
2      0  STON/O2. 3101282   7.9250        S
3      0            113803  53.1000        S
4      0            373450   8.0500        S

In [23]:
passengers_over_40=dd[dd['Age']>40]
passengers_over_40[['Name','Age']]

                                                  Name   Age
6                              McCarthy, Mr. Timothy J  54.0
11                            Bonnell, Miss. Elizabeth  58.0
15                    Hewlett, Mrs. (Mary D Kingcome)   55.0
33                               Wheadon, Mr. Edward H  66.0
35                      Holverson, Mr. Alexander Oskar  42.0
..                                                 ...   ...
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  48.0
865                           Bystrom, Mrs. (Karolina)  42.0
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  47.0
873                        Vander Cruyssen, Mr. Victor  47.0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  56.0

[150 rows x 2 columns]

In [24]:
merged_rows=pd.concat([dd.head(2),dd.tail(2)])
merged_rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q